#!/usr/bin/env python3
"""
ID: WR-SCRIPT-TRAIN-001
Purpose: Train DualBranchEncoder + PoseEstimator on synthetic CSI/pose pairs
         generated by the built-in WiFi-channel simulator.  Saves the best
         checkpoint to weights/simulation_baseline.pth so the system can run
         inference immediately without real router hardware.

Usage:
    python scripts/train_simulation_baseline.py                      # quick (CPU)
    python scripts/train_simulation_baseline.py --epochs 200 --n-samples 20000
    python scripts/train_simulation_baseline.py --resume weights/simulation_baseline.pth
"""
import argparse
import logging
import os
import sys
import time
from pathlib import Path
from typing import Tuple

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader, Dataset, random_split

# Ensure project root is on path
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from wifi_radar.models.encoder import DualBranchEncoder
from wifi_radar.models.pose_estimator import PoseEstimator
from wifi_radar.utils.model_io import load_checkpoint, save_checkpoint

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s  %(message)s",
    datefmt="%H:%M:%S",
)
log = logging.getLogger("train")

# ─────────────────────────────────────────────────────────────────────────── #
# Body template (17-point COCO format, normalised space [-1, 1])              #
# ─────────────────────────────────────────────────────────────────────────── #
_STANDING_POSE = np.array([
    [ 0.00,  0.0,  0.85],   # 0 nose
    [-0.05,  0.0,  0.88],   # 1 left_eye
    [ 0.05,  0.0,  0.88],   # 2 right_eye
    [-0.10,  0.0,  0.83],   # 3 left_ear
    [ 0.10,  0.0,  0.83],   # 4 right_ear
    [-0.20,  0.0,  0.65],   # 5 left_shoulder
    [ 0.20,  0.0,  0.65],   # 6 right_shoulder
    [-0.30,  0.0,  0.35],   # 7 left_elbow
    [ 0.30,  0.0,  0.35],   # 8 right_elbow
    [-0.30,  0.0,  0.05],   # 9 left_wrist
    [ 0.30,  0.0,  0.05],   # 10 right_wrist
    [-0.10,  0.0,  0.25],   # 11 left_hip
    [ 0.10,  0.0,  0.25],   # 12 right_hip
    [-0.12,  0.0, -0.10],   # 13 left_knee
    [ 0.12,  0.0, -0.10],   # 14 right_knee
    [-0.12,  0.0, -0.50],   # 15 left_ankle
    [ 0.12,  0.0, -0.50],   # 16 right_ankle
], dtype=np.float32)

# Arm/leg swing amplitude for walking simulation
_WALK_AMP = np.array([
    [0.0, 0.0, 0.0],   # nose — stationary
    [0.0, 0.0, 0.0],   # eyes
    [0.0, 0.0, 0.0],
    [0.0, 0.0, 0.0],   # ears
    [0.0, 0.0, 0.0],
    [0.0, 0.04, 0.04], # left_shoulder
    [0.0, 0.04, 0.04],
    [0.0, 0.08, 0.10], # left_elbow
    [0.0, 0.08, 0.10],
    [0.0, 0.12, 0.15], # left_wrist
    [0.0, 0.12, 0.15],
    [0.0, 0.02, 0.02], # hips
    [0.0, 0.02, 0.02],
    [0.0, 0.06, 0.12], # knees
    [0.0, 0.06, 0.12],
    [0.0, 0.10, 0.18], # ankles
    [0.0, 0.10, 0.18],
], dtype=np.float32)


def generate_pose(cx: float, cy: float, walking_phase: float = 0.0) -> np.ndarray:
    """Generate a body pose centred at (cx, cy) in normalised space.

    Args:
        cx, cy:        Centre position, both in [−1, 1].
        walking_phase: Phase angle in [0, 2π]; 0 = standing, else walking.

    Returns:
        (17, 3) float32 keypoint array.
    """
    pose = _STANDING_POSE.copy()
    # Translate to person's position
    pose[:, 0] += cx
    pose[:, 1] += cy

    if walking_phase != 0.0:
        # Left limbs lead, right limbs trail by π
        left_idx  = [5, 7, 9, 11, 13, 15]
        right_idx = [6, 8, 10, 12, 14, 16]
        for i in left_idx:
            pose[i] += _WALK_AMP[i] * np.sin(walking_phase)
        for i in right_idx:
            pose[i] += _WALK_AMP[i] * np.sin(walking_phase + np.pi)

    return np.clip(pose, -1.0, 1.0)


def generate_csi(
    x_pos: float,
    y_pos: float,
    num_tx: int = 3,
    num_rx: int = 3,
    num_sub: int = 64,
) -> Tuple[np.ndarray, np.ndarray]:
    """Generate a single synthetic CSI frame for a person at (x_pos, y_pos).

    Args:
        x_pos, y_pos: Person's normalised position in [0, 1].

    Returns:
        amplitude, phase — each (num_tx, num_rx, num_sub) float32.
    """
    amplitude = np.random.rayleigh(scale=1.0, size=(num_tx, num_rx, num_sub)).astype(np.float32)
    phase     = np.random.uniform(-np.pi, np.pi, size=(num_tx, num_rx, num_sub)).astype(np.float32)

    tx_idx = np.arange(num_tx)[:, None, None] / num_tx
    rx_idx = np.arange(num_rx)[None, :, None] / num_rx
    sc_idx = np.arange(num_sub)[None, None, :]

    effect = 0.2 * np.exp(-((tx_idx - x_pos) ** 2 + (rx_idx - y_pos) ** 2) * 10).astype(np.float32)
    sc_fac = np.sin(sc_idx / num_sub * np.pi * 4).astype(np.float32)

    amplitude *= (1 + effect * sc_fac * 0.5)
    phase     += effect * sc_fac * 0.8
    return amplitude, phase


# ─────────────────────────────────────────────────────────────────────────── #
# Dataset                                                                      #
# ─────────────────────────────────────────────────────────────────────────── #

class SimulatedPoseDataset(Dataset):
    """Pre-generated in-memory dataset of (amplitude, phase) → keypoint pairs.

    Args:
        n_samples:    Number of training examples to generate.
        walking_frac: Fraction of samples in walking pose (rest are standing).
        seed:         Random seed for reproducibility.
    """

    def __init__(self, n_samples: int = 8000, walking_frac: float = 0.6, seed: int = 42) -> None:
        rng = np.random.default_rng(seed)
        n_walking = int(n_samples * walking_frac)

        self._amp: list  = []
        self._phase: list = []
        self._kp: list   = []
        self._conf: list = []

        for i in range(n_samples):
            x_pos = float(rng.uniform(0.1, 0.9))
            y_pos = float(rng.uniform(0.1, 0.9))
            phase_angle = float(rng.uniform(0, 2 * np.pi)) if i < n_walking else 0.0

            amp, pha = generate_csi(x_pos, y_pos)
            kp = generate_pose(x_pos * 2 - 1, y_pos * 2 - 1, phase_angle)
            conf = np.ones(17, dtype=np.float32)

            # Small noise on keypoints
            kp += rng.normal(0, 0.02, kp.shape).astype(np.float32)
            np.clip(kp, -1.0, 1.0, out=kp)

            self._amp.append(amp)
            self._phase.append(pha)
            self._kp.append(kp)
            self._conf.append(conf)

    def __len__(self) -> int:
        return len(self._amp)

    def __getitem__(self, idx: int):
        return (
            torch.from_numpy(self._amp[idx]),
            torch.from_numpy(self._phase[idx]),
            torch.from_numpy(self._kp[idx]),
            torch.from_numpy(self._conf[idx]),
        )


# ─────────────────────────────────────────────────────────────────────────── #
# Training loop                                                                #
# ─────────────────────────────────────────────────────────────────────────── #

def train(args: argparse.Namespace) -> None:
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    log.info("Device: %s", device)

    # ── Dataset ───────────────────────────────────────────────────────────
    log.info("Generating %d simulation samples …", args.n_samples)
    t0 = time.time()
    dataset = SimulatedPoseDataset(n_samples=args.n_samples, seed=args.seed)
    val_size  = max(1, int(0.1 * len(dataset)))
    train_ds, val_ds = random_split(
        dataset, [len(dataset) - val_size, val_size],
        generator=torch.Generator().manual_seed(args.seed),
    )
    log.info("Dataset ready  (train=%d  val=%d)  in %.1f s", len(train_ds), len(val_ds), time.time() - t0)

    train_dl = DataLoader(train_ds, batch_size=args.batch_size, shuffle=True,  num_workers=0, pin_memory=(device.type == "cuda"))
    val_dl   = DataLoader(val_ds,   batch_size=args.batch_size, shuffle=False, num_workers=0)

    # ── Models ────────────────────────────────────────────────────────────
    encoder        = DualBranchEncoder().to(device)
    pose_estimator = PoseEstimator().to(device)
    encoder.initialize_weights()

    start_epoch = 0
    best_val    = float("inf")

    if args.resume and os.path.exists(args.resume):
        info = load_checkpoint(encoder, pose_estimator, args.resume, device=device, strict=False)
        start_epoch = info["epoch"] + 1
        best_val    = info["val_loss"]
        log.info("Resumed from epoch %d, best val=%.4f", start_epoch, best_val)

    params = list(encoder.parameters()) + list(pose_estimator.parameters())
    optimizer = torch.optim.Adam(params, lr=args.lr, weight_decay=1e-5)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
        optimizer, T_max=args.epochs, eta_min=args.lr * 0.01
    )
    if start_epoch > 0:
        for _ in range(start_epoch):
            scheduler.step()

    os.makedirs(args.output_dir, exist_ok=True)
    output_path = os.path.join(args.output_dir, "simulation_baseline.pth")

    # ── Epoch loop ────────────────────────────────────────────────────────
    for epoch in range(start_epoch, args.epochs):
        encoder.train()
        pose_estimator.train()
        train_loss = 0.0

        for amp, pha, kp_gt, conf_gt in train_dl:
            amp, pha   = amp.to(device),  pha.to(device)
            kp_gt      = kp_gt.to(device)
            conf_gt    = conf_gt.to(device)

            features               = encoder(amp, pha)
            kp_pred, conf_pred, _  = pose_estimator(features)

            loss_kp   = F.mse_loss(kp_pred, kp_gt)
            loss_conf = F.binary_cross_entropy(conf_pred, conf_gt)
            loss      = loss_kp + 0.1 * loss_conf

            optimizer.zero_grad()
            loss.backward()
            torch.nn.utils.clip_grad_norm_(params, max_norm=1.0)
            optimizer.step()
            train_loss += loss.item()

        scheduler.step()
        train_loss /= len(train_dl)

        # ── Validation ────────────────────────────────────────────────────
        encoder.eval()
        pose_estimator.eval()
        val_loss = 0.0
        with torch.no_grad():
            for amp, pha, kp_gt, conf_gt in val_dl:
                amp, pha = amp.to(device), pha.to(device)
                kp_gt    = kp_gt.to(device)
                conf_gt  = conf_gt.to(device)
                features              = encoder(amp, pha)
                kp_pred, conf_pred, _ = pose_estimator(features)
                loss_kp   = F.mse_loss(kp_pred, kp_gt)
                loss_conf = F.binary_cross_entropy(conf_pred, conf_gt)
                val_loss += (loss_kp + 0.1 * loss_conf).item()
        val_loss /= len(val_dl)

        log.info(
            "Epoch %3d/%d  lr=%.1e  train=%.4f  val=%.4f%s",
            epoch + 1, args.epochs,
            optimizer.param_groups[0]["lr"],
            train_loss, val_loss,
            "  ← best" if val_loss < best_val else "",
        )

        if val_loss < best_val:
            best_val = val_loss
            save_checkpoint(
                encoder, pose_estimator, output_path,
                metadata={"trained_on": "simulation", "n_samples": args.n_samples},
                epoch=epoch,
                val_loss=best_val,
            )

    log.info("Training complete.  Best val loss: %.4f  →  %s", best_val, output_path)


# ─────────────────────────────────────────────────────────────────────────── #
# CLI                                                                          #
# ─────────────────────────────────────────────────────────────────────────── #

def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Train WiFi-Radar simulation baseline")
    p.add_argument("--epochs",     type=int,   default=80,      help="Training epochs")
    p.add_argument("--n-samples",  type=int,   default=8000,    help="Synthetic dataset size")
    p.add_argument("--batch-size", type=int,   default=64,      help="Mini-batch size")
    p.add_argument("--lr",         type=float, default=1e-3,    help="Initial learning rate")
    p.add_argument("--seed",       type=int,   default=42,      help="RNG seed")
    p.add_argument("--output-dir", type=str,   default="weights", help="Checkpoint output dir")
    p.add_argument("--resume",     type=str,   default=None,    help="Path to checkpoint to resume from")
    return p.parse_args()


if __name__ == "__main__":
    train(parse_args())
